=== americanstone/IAD_Final/image/submissions/1/1/Group_1/JZHW1/prob2.dtd
<!ELEMENT person (first_name, last_name)>
<!ATTLIST person born CDATA #IMPLIED
                 died CDATA #IMPLIED>
 
<!-- born and died dates are in the form yyyy/mm/dd -->
<!ELEMENT date   (month, day, year)>
<!ELEMENT month  (#PCDATA)>
<!ELEMENT day    (#PCDATA)>
<!ELEMENT year   (#PCDATA)>
 
 
<!ELEMENT profession (#PCDATA)>
<!ELEMENT footnote   (#PCDATA)>
<!ATTLIST footnote source CDATA #REQUIRED>
 
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name  (#PCDATA)>
 
<!ELEMENT image EMPTY>
<!ATTLIST image source CDATA   #REQUIRED
                width  NMTOKEN #REQUIRED
                height NMTOKEN #REQUIRED
                ALT    CDATA   #IMPLIED
> 
<!ENTITY % top_level "( #PCDATA | image | paragraph | definition
                      | person | profession | emphasize | last_name
                      | first_name | footnote | date )*">
 
<!ELEMENT paragraph  %top_level; >
<!ELEMENT definition %top_level; >
<!ELEMENT emphasize  %top_level; >
<!ELEMENT biography  %top_level; >

=== americanstone/IAD_Final/image/submissions/1/1/Group_1/JZHW1/prob2.xml
<?xml version="1.0"?>
<!--  prob2.xml
      Jing Zhao
      CSC 626: Web Technologies
      Assignment 1
      2/8/2012 -->
<!DOCTYPE biography SYSTEM "prob2.dtd">
<biography>
	<paragraph>
		<definition>
			<person born="1955/02/24" died="2011/10/05">
				<first_name>
					Steve
				</first_name>
				<last_name>
					Jobs
				</last_name>
			</person>
		</definition>
		<definition>
			<profession>
				Apple CEO
			</profession>
			<footnote source="published">
				Jobs Biography
			</footnote>
		</definition>
	</paragraph>
	<paragraph>
		<emphasize>
			<date>
				<month>
					Feb.
				</month>
				<day>
					2nd
				</day>
				<year>
					2006
				</year>
			</date>
		</emphasize>
	</paragraph>
	<image source="jobs.jpg" width="20px" height="30px" />
</biography>
